import {
  AlignLeft,
  BookOpen,
  Camera,
  Clapperboard,
  Copy,
  Flame,
  Grid2X2,
  ImageIcon,
  Layers,
  LayoutGrid,
  Music,
  Package,
  PenLine,
  RefreshCw,
  ScrollText,
  Shirt,
  ShoppingBag,
  Smile,
  Sparkles,
  Tag,
  UserRound,
  UtensilsCrossed,
  Video,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";
import type { SkillIconName } from "@/lib/skills";

export const SKILL_ICONS: Record<SkillIconName, LucideIcon> = {
  scroll: ScrollText,
  copy: Copy,
  video: Video,
  book: BookOpen,
  spark: RefreshCw,
  wand: WandSparkles,
  smile: Smile,
  layout: LayoutGrid,
  pen: PenLine,
  bag: ShoppingBag,
  user: UserRound,
  shirt: Shirt,
  music: Music,
  tag: Tag,
  grid: Grid2X2,
  align: AlignLeft,
  layers: Layers,
  image: ImageIcon,
  sparkles: Sparkles,
  clapper: Clapperboard,
  box: Package,
  flame: Flame,
  camera: Camera,
  utensils: UtensilsCrossed,
};
