import { sanitizeNextPath } from "./safe-redirect";

export const PASSWORD_RECOVERY_PROOF_COOKIE =
  "kelolako_password_recovery_proof";
export const PASSWORD_RECOVERY_PROOF_MAX_AGE_SEC = 365 * 24 * 60 * 60;

export function isPasswordRecoveryCallback(
  flow: string | null,
  next: string | null | undefined,
): boolean {
  if (flow === "recovery") return true;
  if (flow !== null) return false;
  try {
    return (
      new URL(sanitizeNextPath(next), "https://internal.invalid").pathname ===
      "/reset-password"
    );
  } catch {
    return false;
  }
}

export function passwordRecoveryDestinationFromCallback(
  flow: string | null,
  next: string | null | undefined,
): string | null {
  if (flow === "recovery") {
    return passwordRecoveryDestinationFromLanding(next) ?? "/dashboard";
  }
  return isPasswordRecoveryCallback(flow, next) ? "/dashboard" : null;
}

/**
 * Recognize the reset landing generated by passwordResetCallbackUrl and
 * recover its final destination. A normal authenticated session must not be
 * able to opt into the trusted reset UI with only `?resetPassword=1`.
 */
export function passwordRecoveryDestinationFromLanding(
  resetLanding: string | null | undefined,
): string | null {
  const safeLanding = sanitizeNextPath(resetLanding);

  try {
    const landing = new URL(safeLanding, "https://internal.invalid");
    if (
      landing.pathname !== "/dashboard" ||
      landing.searchParams.get("resetPassword") !== "1"
    ) {
      return null;
    }
    return sanitizeNextPath(landing.searchParams.get("next"));
  } catch {
    return null;
  }
}

export function passwordRecoveryProofValue(
  destination: string | null | undefined,
): string {
  return encodeURIComponent(sanitizeNextPath(destination));
}

export function passwordRecoveryDestinationFromProof(
  proof: string | null | undefined,
): string | null {
  if (!proof) return null;
  try {
    return sanitizeNextPath(decodeURIComponent(proof));
  } catch {
    return null;
  }
}

export type PasswordRecoveryGateDecision =
  | "allow"
  | "require-reset-page"
  | "reject-api";

export function passwordRecoveryGateDecision({
  authenticated,
  recoveryDestination,
  requestPathWithSearch,
  isApi,
  isRecoveryStateApi,
}: {
  authenticated: boolean;
  recoveryDestination: string | null;
  requestPathWithSearch: string;
  isApi: boolean;
  isRecoveryStateApi: boolean;
}): PasswordRecoveryGateDecision {
  if (!authenticated || !recoveryDestination || isRecoveryStateApi) {
    return "allow";
  }
  if (isApi) return "reject-api";
  return passwordRecoveryDestinationFromLanding(requestPathWithSearch) ===
    recoveryDestination
    ? "allow"
    : "require-reset-page";
}
